services:
  rabbitmq:
    image: rabbitmq:4-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q check_running
      interval: 10s
      retries: 12

  inventory:
    build: ./inventory
    image: korp/inventory:dev
    init: true
    ports:
      - "8000:8000"
    environment:
      GO_ENV: ${GO_ENV:-development}
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
      DB_HOST: inventory_db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 1234
    volumes:
      - ./inventory:/go/src/app
      - gomodcache:/go/pkg/mod
    depends_on:
      inventory_db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    command: sleep infinity

  inventory_db:
    image: postgres:18
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: pg_isready -h 127.0.0.1 -U postgres
      interval: 5s
      retries: 12

  billing:
    build: ./billing
    image: korp/billing:dev
    init: true
    ports:
      - "8001:8001"
    environment:
      GO_ENV: ${GO_ENV:-development}
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
      DB_HOST: billing_db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 1234
    volumes:
      - ./billing:/go/src/app
      - gomodcache:/go/pkg/mod
    depends_on:
      billing_db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    command: sleep infinity

  billing_db:
    image: postgres:18
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
    ports:
      - "5434:5432"
    volumes:
      - billing_pgdata:/var/lib/postgresql
    healthcheck:
      test: pg_isready -h 127.0.0.1 -U postgres
      interval: 5s
      retries: 12

  frontend:
    build:
      context: ./frontend
      target: dev
    image: korp/frontend:dev
    environment:
      INVENTORY_API_URL: http://inventory:8000
      BILLING_API_URL: http://billing:8001
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - inventory
      - billing

volumes:
  rabbitmqdata: {}
  pgdata: {}
  billing_pgdata: {}
  gomodcache: {}
